{% set data= load_setup_py_data() %}
package:
  name: ts-atpneumaticssimulator
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_atpneumatics_simulator = lsst.ts.atpneumaticssimulator:run_atpneumatics_simulator

test:
  requires:
    - ts-conda-build =0.4
    - ts-dds
    - ts-xml {{ xml_version }}
    - ts-salobj {{ salobj_version }}
    - ts-attcpip
    - ts-tcpip >=1.1.1
    - ts-utils
  source_files:
    - bin
    - pyproject.toml
    - python
    - tests
  commands:
    - py.test

requirements:
  host:
    - pip
    - python {{ python }}
    - setuptools
    - setuptools_scm
  build:
    - python {{ python }}
    - setuptools
    - setuptools_scm
  run:
    - python {{ python }}
    - ts-xml
    - ts-salobj
    - ts-attcpip
    - ts-tcpip >=1.1.1
    - ts-utils
